

CREATE TABLE usuarios (
    id BIGINT NOT NULL,
    ativo BOOLEAN NOT NULL,
    email VARCHAR(200) NOT NULL,
    nome_completo VARCHAR(255) NOT NULL,
    perfil VARCHAR(255) NOT NULL CHECK (perfil IN ('ADMIN','OPERADOR')),
    senha VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);
ALTER TABLE usuarios ADD CONSTRAINT uk_usuario_email UNIQUE (email);

CREATE TABLE produtos (
    id BIGINT NOT NULL,
    categoria VARCHAR(255),
    codigo VARCHAR(50) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    preco_unitario NUMERIC(16, 2) NOT NULL,
    quantidade_estoque INTEGER NOT NULL,
    PRIMARY KEY (id)
);
ALTER TABLE produtos ADD CONSTRAINT uk_produto_codigo UNIQUE (codigo);

CREATE TABLE vendas (
    id BIGINT NOT NULL,
    data_hora TIMESTAMP(6) NOT NULL,
    troco NUMERIC(38, 2) NOT NULL,
    valor_recebido NUMERIC(38, 2) NOT NULL,
    valor_total NUMERIC(38, 2) NOT NULL,
    usuario_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE itens_venda (
    id BIGINT NOT NULL,
    preco_unitario NUMERIC(16, 2) NOT NULL,
    quantidade INTEGER NOT NULL,
    subtotal NUMERIC(16, 2) NOT NULL,
    produto_id BIGINT NOT NULL,
    venda_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE movimentacoes_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_hora TIMESTAMP(6) NOT NULL,
    motivo VARCHAR(255) NOT NULL,
    quantidade INTEGER NOT NULL,
    tipo VARCHAR(255) NOT NULL CHECK (tipo IN ('ENTRADA','AJUSTE_POSITIVO','AJUSTE_NEGATIVO')),
    produto_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE vendas ADD CONSTRAINT fk_venda_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios;
ALTER TABLE itens_venda ADD CONSTRAINT fk_item_produto FOREIGN KEY (produto_id) REFERENCES produtos;
ALTER TABLE itens_venda ADD CONSTRAINT fk_item_venda FOREIGN KEY (venda_id) REFERENCES vendas;
ALTER TABLE movimentacoes_estoque ADD CONSTRAINT fk_mov_produto FOREIGN KEY (produto_id) REFERENCES produtos;
ALTER TABLE movimentacoes_estoque ADD CONSTRAINT fk_mov_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios;